// ignore_for_file: use_null_aware_elements

/// Factory functions for the operation payloads used by the relay protocol.
///
/// These return plain JSON maps so they can be stored directly in an
/// [OperationEnvelope.payload]. They mirror the payloads generated by the web
/// frontend.
class OperationPayloads {
  OperationPayloads._();

  static Map<String, dynamic> nodeCreate({
    required String nodeId,
    required String kind,
    String? parentId,
    List<String>? classIds,
    String? icon,
    String? color,
    List<Map<String, dynamic>>? initialContent,
  }) => {
        'nodeId': nodeId,
        'kind': kind,
        if (parentId != null) 'parentId': parentId,
        'classIds': classIds ?? <String>[],
        if (icon != null) 'icon': icon,
        if (color != null) 'color': color,
        if (initialContent != null) 'initialContent': initialContent,
      };

  static Map<String, dynamic> nodeUpdateContent({
    required String nodeId,
    List<Map<String, dynamic>>? content,
  }) => {
        'nodeId': nodeId,
        if (content != null) 'content': content,
      };

  static Map<String, dynamic> nodeDelete({required String nodeId}) => {
        'nodeId': nodeId,
      };

  static Map<String, dynamic> nodeArchive({required String nodeId}) => {
        'nodeId': nodeId,
      };

  static Map<String, dynamic> nodeRestore({required String nodeId}) => {
        'nodeId': nodeId,
      };

  static Map<String, dynamic> nodeUpdateIcon({
    required String nodeId,
    String? icon,
  }) =>
      {
        'nodeId': nodeId,
        'icon': icon,
      };

  static Map<String, dynamic> nodeUpdateColor({
    required String nodeId,
    String? color,
  }) =>
      {
        'nodeId': nodeId,
        'color': color,
      };

  static Map<String, dynamic> nodeMove({
    required String nodeId,
    required String? newParentId,
    int? newIndex,
  }) =>
      {
        'nodeId': nodeId,
        'newParentId': newParentId,
        if (newIndex != null) 'newIndex': newIndex,
      };

  static Map<String, dynamic> classAssign({
    required String nodeId,
    required String classId,
  }) =>
      {
        'nodeId': nodeId,
        'classId': classId,
      };

  static Map<String, dynamic> classUnassign({
    required String nodeId,
    required String classId,
  }) =>
      {
        'nodeId': nodeId,
        'classId': classId,
      };

  static Map<String, dynamic> classCreate({
    required String classId,
    required String name,
    String? icon,
    String? color,
    String? description,
    List<String>? extendsClassIds,
  }) =>
      {
        'classId': classId,
        'name': name,
        if (icon != null) 'icon': icon,
        if (color != null) 'color': color,
        if (description != null) 'description': description,
        if (extendsClassIds != null) 'extends': extendsClassIds,
      };

  static Map<String, dynamic> classUpdate({
    required String classId,
    String? name,
    String? icon,
    String? color,
    String? description,
  }) =>
      {
        'classId': classId,
        if (name != null) 'name': name,
        if (icon != null) 'icon': icon,
        if (color != null) 'color': color,
        if (description != null) 'description': description,
      };

  static Map<String, dynamic> classDelete({required String classId}) => {
        'classId': classId,
      };

  static Map<String, dynamic> classSetExtends({
    required String classId,
    required List<String> extendsClassIds,
  }) =>
      {
        'classId': classId,
        'extendsClassIds': extendsClassIds,
      };

  static Map<String, dynamic> propertySet({
    required String propertyValueId,
    required String nodeId,
    required String schemaId,
    required dynamic value,
    int index = 0,
  }) =>
      {
        'propertyValueId': propertyValueId,
        'nodeId': nodeId,
        'schemaId': schemaId,
        'value': value,
        'index': index,
      };

  static Map<String, dynamic> propertyUnset({
    required String nodeId,
    required String schemaId,
    int index = 0,
  }) =>
      {
        'nodeId': nodeId,
        'schemaId': schemaId,
        'index': index,
      };

  static Map<String, dynamic> taskRecordCompletion({
    required String nodeId,
    required String completionId,
    String? completedAt,
    String? scheduledDate,
    String? deadlineDate,
    String? status,
  }) => {
        'nodeId': nodeId,
        'completionId': completionId,
        if (completedAt != null) 'completedAt': completedAt,
        if (scheduledDate != null) 'scheduledDate': scheduledDate,
        if (deadlineDate != null) 'deadlineDate': deadlineDate,
        if (status != null) 'status': status,
      };

  static Map<String, dynamic> taskDeleteCompletion({
    required String nodeId,
    required String completionId,
  }) =>
      {
        'nodeId': nodeId,
        'completionId': completionId,
      };

  static Map<String, dynamic> userFavoriteAdd({required String nodeId}) => {
        'nodeId': nodeId,
      };

  static Map<String, dynamic> userFavoriteRemove({required String nodeId}) => {
        'nodeId': nodeId,
      };

  static Map<String, dynamic> userFavoriteReorder({
    required List<String> nodeIds,
  }) =>
      {
        'nodeIds': nodeIds,
      };
}
